### ISSUE TITLE
前端调试技巧

### ISSUE THREAD

**Issue by monkindey** [monkindey/KihoSaid#4]
前端调试是一个前端工程师的软素质

* 循环
* 递归
* 死循环

**Comment by monkindey** [comment]
**不再更新**

**Comment by monkindey** [comment]
### [Javascript debugging tips using the Chrome Dev Tools, deb.js and more](http://blog.angular-university.io/javascript-debugging-tips-using-chrome-dev-tools-deb-js-and-more/)

里面有很多技巧值得我们去学习

**Comment by monkindey** [comment]
### [Debugging Tips and Tricks](https://css-tricks.com/debugging-tips-tricks/)

**Comment by monkindey** [comment]
### 二分法调试

Dan https://twitter.com/dan_abramov/status/848913169179439104

**Comment by monkindey** [comment]
### [PerformanceObserver](https://github.com/tdresser/performance-observer-tracing)

从[chrome://tracing/](chrome://tracing/) 获取数据

**Comment by monkindey** [comment]
### 暴露更多信息

比如: 

* webpack --display-error-details https://github.com/monkindey/note/issues/9#issuecomment-249884216
* https://twitter.com/dan_abramov/status/875715680447942657
   ```js
   new Error().stack
   ```

**Comment by monkindey** [comment]
### 找到谁调用它

```js
new Error().stack
```

今天写了一个webpack插件, 是有关webpack dev server, 死活找不到为什么webpack会watch呢? 
感觉应该是webpack dev server设置, 但是在它的代码里找不到, 所以我就在webpack的代码里有一个watch函数, 如下

```js
watch(watchOptions, handler) {
  this.fileTimestamps = {};
  this.contextTimestamps = {};
  const watching = new Watching(this, watchOptions, handler);
  throw new Error(); // 加上这个报错
  return watching;
}
```

打印出来的报错栈(省去一些敏感信息)

```dash
 at Compiler.watch (node_modules/webpack/lib/Compiler.js:228:9)
    at Object.startWatch (node_modules/webpack-dev-middleware/lib/Shared.js:176:29)
    at Shared (node_modules/webpack-dev-middleware/lib/Shared.js:238:8)
    at module.exports (node_modules/webpack-dev-middleware/middleware.js:22:15)
    at new Server (node_modules/webpack-dev-server/lib/Server.js:69:20)
    at createDevServer (scripts/start.js:36:21)
    at fse.pathExists.then.isExist (start.js:83:5)
    at <anonymous>
```

这个时候我就知道原来是`webpack-dev-middleware`[这段代码](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/Shared.js#L238)干的好事哈

**Comment by monkindey** [comment]
### 常量法

先带入一些写死的数据, 看看能不能跑得通

**Comment by monkindey** [comment]
### 最小可复现代码

咱们有时候要报bug给开源项目, 我们最好整理一份最小可复现的代码, 方便owner帮你找出问题。
但是其实在咱们整理这一份的过程中, 说不定bug已经被我们找出来了。

**Comment by monkindey** [comment]
### [getEventListener](https://github.com/monkindey/note/issues/15#issuecomment-286022340)

**Comment by monkindey** [comment]
### Automatically pause on any exception

https://github.com/monkindey/note/issues/15#issuecomment-286747397

**Comment by monkindey** [comment]
### Breakpoint on access to a property

https://github.com/monkindey/note/issues/15#issuecomment-287014611

**Comment by monkindey** [comment]
### 查看网页所有元素的总大小

有一个场景就是我import所有的ant css样式, 但是我用了`babel-plugin-import`, 想看看它引入之后两者的区别, 但是因为css是通过js动态插入`<style>`标签方式引入的, 所以不能从network看到对应的css请求跟大小。

那怎么看到对应的大小呢? 可以查看network底部的transfer值

* https://www.v2ex.com/t/33043
* https://developers.google.com/web/tools/chrome-devtools/network-performance/reference 关键字查询 `View the total download size`

**Comment by monkindey** [comment]
### [How to debug Front-end: Console](https://blog.pragmatists.com/how-to-debug-front-end-console-3456e4ee5504)

怎么使用`Console`

**Comment by monkindey** [comment]
### [Learn How To Debug JavaScript with Chrome DevTools](https://codeburst.io/learn-how-to-debug-javascript-with-chrome-devtools-9514c58479db)

Step by Step 教你怎么debug JavaScript问题，通过一个例子来解释我觉得是太清晰明了了。

**Comment by monkindey** [comment]
### [Debugging React performance with React 16 and Chrome Devtools.](https://building.calibreapp.com/debugging-react-performance-with-react-16-and-chrome-devtools-c90698a522ad)

React + `Chrome Devtools Performance`

#### 更多内容

* [Performance Analysis Reference](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference)
